# Generated by Django 5.0.6 on 2024-06-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.day'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='room',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
