# Generated by Django 5.0.6 on 2024-07-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_timetableentry_day_alter_timetableentry_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
