# Generated by Django 5.0.6 on 2024-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetableentry_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='rammy rammy', max_length=250),
            preserve_default=False,
        ),
    ]
